words = [
    "COMPOSTER",
    "CRAFTER",
    "DEEPSLATE",
    "ENDER",
    "EYEBLOSSOM",
    "FLETCHING",
    "FROGLIGHT",
    "GLOWSTONE",
    "NETHERITE",
    "NYLIUM",
    "OCHRE",
    "OXEYE",
    "PEARLESCENT",
    "PODZOL",
    "PROPAGULE",
    "PURPUR",
    "Prismarine",
    "RESPAWN",
    "SCULK",
    "SEAGRASS",
    "SHROOMLIGHT",
    "SHULKER",
    "SMITHING",
    "TORCHFLOWER",
    "gamemode",
    "gamerules",
    "lapis",
    "netherrack",
    "xyz",
]
