words = [
    "AXE",
    "BOBBER",
    "CHAINMAIL",
    "CHESTPLATE",
    "COMPOSTER",
    "CRAFTER",
    "DEEPSLATE",
    "DRIPLEAF",
    "ELYTRA",
    "ENDER",
    "ENDERMAN",
    "ENDERMITE",
    "EYEBLOSSOM",
    "FLETCHING",
    "FROGLIGHT",
    "GHAST",
    "GLOWSTONE",
    "GUSTER",
    "HOGLIN",
    "ILLUSIONER",
    "MASONED",
    "MELLOHI",
    "MINECART",
    "MOJANG",
    "MOOSHROOM",
    "NETHERITE",
    "NYLIUM",
    "OCHRE",
    "OTHERSIDE",
    "OXEYE",
    "PEARLESCENT",
    "PICKAXE",
    "PIGLIN",
    "PIGSTEP",
    "PODZOL",
    "PORKCHOP",
    "PROPAGULE",
    "PUFFERFISH",
    "PURPUR",
    "Prismarine",
    "RESPAWN",
    "SCULK",
    "SEAGRASS",
    "SHROOMLIGHT",
    "SHULKER",
    "SMITHING",
    "STAL",
    "STRAD",
    "Slimeball",
    "TORCHFLOWER",
    "WAYFINDER",
    "ZOGLIN",
    "ZOMBIFIED",
    "gamemode",
    "gamerules",
    "lapis",
    "netherrack",
    "overworld",
    "xyz",
]
