words = [
    "AAB",
    "AABB",
    "AXE",
    "BADLUCK",
    "BADOMEN",
    "BASEDRUM",
    "BOBBER",
    "BREATHOFTHENAUTILUS",
    "CHAINMAIL",
    "CHESTPLATE",
    "COMPOSTER",
    "CONDUITPOWER",
    "COSY",
    "CRAFTER",
    "DEEPSLATE",
    "DOLPHINSGRACE",
    "DRIPLEAF",
    "ELYTRA",
    "ENDER",
    "ENDERMAN",
    "ENDERMITE",
    "EYEBLOSSOM",
    "FIRERESISTANCE",
    "FLETCHING",
    "FROGLIGHT",
    "GHAST",
    "GLOWSTONE",
    "GUSTER",
    "HEALTHBOOST",
    "HEROOFTHEVILLAGE",
    "HOGLIN",
    "ILLUSIONER",
    "INSTANTDAMAGE",
    "INSTANTHEALTH",
    "Interactable",
    "JUMPBOOST",
    "KNOCKBACK",
    "MASONED",
    "MELLOHI",
    "MINECART",
    "MININGFATIGUE",
    "MOJANG",
    "MOOSHROOM",
    "MULTISHOT",
    "Minecraft's",
    "Mojang's",
    "NBT",
    "NETHERITE",
    "NIGHTVISION",
    "NYLIUM",
    "OCHRE",
    "OTHERSIDE",
    "OXEYE",
    "PEARLESCENT",
    "PICKAXE",
    "PIGLIN",
    "PIGSTEP",
    "PLING",
    "PODZOL",
    "PORKCHOP",
    "PROPAGULE",
    "PUFFERFISH",
    "PURPUR",
    "Prismarine",
    "RAIDOMEN",
    "RESPAWN",
    "Ren'",
    "SCULK",
    "SEAGRASS",
    "SHROOMLIGHT",
    "SHULKER",
    "SLOWFALLING",
    "SMITHING",
    "SNBT",
    "STAL",
    "STRAD",
    "Slimeball",
    "TORCHFLOWER",
    "TRIALOMEN",
    "UNBREAKING",
    "WATERBREATHING",
    "WAYFINDER",
    "WINDCHARGED",
    "ZOGLIN",
    "ZOMBIFIED",
    "aiomcrcon",
    "datapack",
    "datapacks",
    "gamemode",
    "gamerules",
    "grimmclub",
    "lapis",
    "mcfunction",
    "mcmeta",
    "mcrcon",
    "netherrack",
    "overworld",
    "pathlib",
    "playerdata",
    "pth",
    "rcon",
    "repo's",
    "setblock",
    "tellraw",
    "xyz",
]
