"""Emit the IR as an installable datapack tree on disk (optionally zipped).

Writes ``pack.mcmeta`` with the target's ``pack_format`` (+ ``supported_formats``
band), the version-correct folder scheme (singular ``function`` on 1.21+, plural
``functions`` earlier), every ``.mcfunction`` rendered through the
:class:`~.dialect.Dialect`, the ``minecraft:load`` / ``minecraft:tick`` tags, any
JSON resources, and a generated ``INSTALL.md``.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Any

from grimmcraft_compiler.dialect import Dialect
from grimmcraft_compiler.ir import Datapack, Function, FunctionTag, Resource
from grimmcraft_compiler.target import Target
from grimmcraft_compiler.version import VersionInfo

# singular resource category -> plural (used on pre-1.21 folder scheme).
_PLURALS = {
    "function": "functions",
    "loot_table": "loot_tables",
    "recipe": "recipes",
    "advancement": "advancements",
    "predicate": "predicates",
    "item_modifier": "item_modifiers",
}


def category_dir(category: str, info: VersionInfo) -> str:
    """The on-disk folder name for a resource ``category`` at this version."""
    if info.singular_folders:
        return category
    return _PLURALS.get(category, category + "s")


def pack_mcmeta(pack: Datapack, info: VersionInfo) -> dict[str, Any]:
    """The ``pack.mcmeta`` document for this target."""
    lo, hi = info.supported_formats
    return {
        "pack": {
            "pack_format": info.pack_format,
            "description": pack.description,
            "supported_formats": {"min_inclusive": lo, "max_inclusive": hi},
        }
    }


def render_function(function: Function, dialect: Dialect) -> str:
    """Render one function to its full ``.mcfunction`` file text."""
    lines: list[str] = []
    if function.comment:
        lines.append(f"# {function.comment}")
    lines.extend(dialect.render(command) for command in function.commands)
    return "\n".join(lines) + "\n"


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _function_path(root: Path, function: Function, info: VersionInfo) -> Path:
    fdir = category_dir("function", info)
    return root / "data" / function.id.namespace / fdir / f"{function.id.path}.mcfunction"


def _tag_path(root: Path, tag: FunctionTag, info: VersionInfo) -> Path:
    fdir = category_dir("function", info)
    return root / "data" / tag.id.namespace / "tags" / fdir / f"{tag.id.path}.json"


def _resource_path(root: Path, resource: Resource, info: VersionInfo) -> Path:
    cdir = category_dir(resource.category, info)
    return root / "data" / resource.id.namespace / cdir / f"{resource.id.path}.json"


def emit(
    pack: Datapack,
    target: Target,
    out_dir: Path,
    *,
    zip_output: bool = False,
) -> Path:
    """Write ``pack`` to ``out_dir`` for ``target``; return the pack path.

    ``out_dir`` is the datapack directory itself (created fresh — an existing one
    is replaced).  With ``zip_output`` the tree is zipped and the ``.zip`` path is
    returned instead.
    """
    info = target.info
    dialect = Dialect(target)
    root = Path(out_dir)
    if root.exists():
        shutil.rmtree(root)
    root.mkdir(parents=True)

    _write(
        root / "pack.mcmeta",
        json.dumps(pack_mcmeta(pack, info), indent=2, ensure_ascii=False) + "\n",
    )

    for function in pack.functions:
        _write(_function_path(root, function, info), render_function(function, dialect))

    for tag in pack.tags:
        content = {"values": [str(member) for member in tag.values]}
        _write(
            _tag_path(root, tag, info),
            json.dumps(content, indent=2, ensure_ascii=False) + "\n",
        )

    for resource in pack.resources:
        _write(
            _resource_path(root, resource, info),
            json.dumps(resource.content, indent=2, ensure_ascii=False) + "\n",
        )

    _write(root / "INSTALL.md", _install_readme(pack, target))

    if zip_output:
        archive = shutil.make_archive(str(root), "zip", root_dir=root)
        return Path(archive)
    return root


def _install_readme(pack: Datapack, target: Target) -> str:
    """Generate install + test instructions for the emitted pack."""
    triggers = sorted(
        str(f.id) for f in pack.functions if "/on_" in f.id.path
    )
    trigger_lines = "\n".join(f"- `/function {t}`" for t in triggers) or "- (none)"
    folder = "function" if target.info.singular_folders else "functions"
    return f"""# {pack.namespace} datapack

Generated by **grimmcraft-compile** for Minecraft **{target.version}**
({target.flavor.value}), `pack_format` {target.info.pack_format}, folder scheme
`data/<ns>/{folder}/…`.

## Install

**Single-player world**

1. Copy this folder (or its `.zip`) into
   `saves/<world>/datapacks/`.
2. In-game run `/reload` (or rejoin the world).
3. Confirm it loaded with `/datapack list` — you should see `{pack.namespace}`.

**Dedicated server**

1. Copy it into `<server>/world/datapacks/`.
2. Run `/reload` from the console or an op.

The `minecraft:load` hook initialises each machine's state; if the pack has a
`minecraft:tick` hook it runs the per-tick loops automatically.

## Try it

Fire an event by calling its trigger function:

{trigger_lines}

State is tracked in the `grimmcraft_state` scoreboard objective — inspect it with:

- `/scoreboard players list`
- `/scoreboard objectives setdisplay sidebar grimmcraft_state`
"""
