"""Auto-generated from PrismarineJS/minecraft-data.
Minecraft Java Edition 1.21.11 — 157 entity types.

Each member's .value is the integer registry id for this version;
.string_id is the namespaced id (e.g. 'minecraft:zombie').
.display_name is the human label.
.type is the entity type (e.g. 'mob', 'object').
.category groups them (e.g. 'Hostile mobs').
NOTE: numeric ids are stable within a version but change between
versions (Java has no permanent numeric ids since 1.13).
Do not edit by hand; regenerate with _generate/entities.py."""

from grimmclub_standardlib import Enum


class Entity(Enum):
    def __new__(cls, num_id, string_id, display_name, type, category):
        obj = object.__new__(cls)
        obj._value_ = num_id
        obj.string_id = string_id
        obj.display_name = display_name
        obj.type = type
        obj.category = category
        return obj

    ACACIA_BOAT = (0, "minecraft:acacia_boat", "Acacia Boat", "other", "Vehicles")
    ACACIA_CHEST_BOAT = (1, "minecraft:acacia_chest_boat", "Acacia Boat with Chest", "other", "Vehicles")
    ALLAY = (2, "minecraft:allay", "Allay", "mob", "Passive mobs")
    AREA_EFFECT_CLOUD = (3, "minecraft:area_effect_cloud", "Area Effect Cloud", "other", "UNKNOWN")
    ARMADILLO = (4, "minecraft:armadillo", "Armadillo", "animal", "Passive mobs")
    ARMOR_STAND = (5, "minecraft:armor_stand", "Armor Stand", "living", "Immobile")
    ARROW = (6, "minecraft:arrow", "Arrow", "projectile", "Projectiles")
    AXOLOTL = (7, "minecraft:axolotl", "Axolotl", "animal", "Passive mobs")
    BAMBOO_CHEST_RAFT = (8, "minecraft:bamboo_chest_raft", "Bamboo Raft with Chest", "other", "Vehicles")
    BAMBOO_RAFT = (9, "minecraft:bamboo_raft", "Bamboo Raft", "other", "Vehicles")
    BAT = (10, "minecraft:bat", "Bat", "ambient", "UNKNOWN")
    BEE = (11, "minecraft:bee", "Bee", "animal", "Passive mobs")
    BIRCH_BOAT = (12, "minecraft:birch_boat", "Birch Boat", "other", "Vehicles")
    BIRCH_CHEST_BOAT = (13, "minecraft:birch_chest_boat", "Birch Boat with Chest", "other", "Vehicles")
    BLAZE = (14, "minecraft:blaze", "Blaze", "hostile", "Hostile mobs")
    BLOCK_DISPLAY = (15, "minecraft:block_display", "Block Display", "other", "UNKNOWN")
    BOGGED = (16, "minecraft:bogged", "Bogged", "hostile", "Hostile mobs")
    BREEZE = (17, "minecraft:breeze", "Breeze", "hostile", "Hostile mobs")
    BREEZE_WIND_CHARGE = (18, "minecraft:breeze_wind_charge", "Wind Charge", "projectile", "Projectiles")
    CAMEL = (19, "minecraft:camel", "Camel", "animal", "Passive mobs")
    CAMEL_HUSK = (20, "minecraft:camel_husk", "Camel Husk", "animal", "Passive mobs")
    CAT = (21, "minecraft:cat", "Cat", "animal", "Passive mobs")
    CAVE_SPIDER = (22, "minecraft:cave_spider", "Cave Spider", "hostile", "Hostile mobs")
    CHERRY_BOAT = (23, "minecraft:cherry_boat", "Cherry Boat", "other", "Vehicles")
    CHERRY_CHEST_BOAT = (24, "minecraft:cherry_chest_boat", "Cherry Boat with Chest", "other", "Vehicles")
    CHEST_MINECART = (25, "minecraft:chest_minecart", "Minecart with Chest", "other", "Vehicles")
    CHICKEN = (26, "minecraft:chicken", "Chicken", "animal", "Passive mobs")
    COD = (27, "minecraft:cod", "Cod", "mob", "Passive mobs")
    COPPER_GOLEM = (28, "minecraft:copper_golem", "Copper Golem", "mob", "Passive mobs")
    COMMAND_BLOCK_MINECART = (29, "minecraft:command_block_minecart", "Minecart with Command Block", "other", "Vehicles")
    COW = (30, "minecraft:cow", "Cow", "animal", "Passive mobs")
    CREAKING = (31, "minecraft:creaking", "Creaking", "hostile", "Hostile mobs")
    CREEPER = (32, "minecraft:creeper", "Creeper", "hostile", "Hostile mobs")
    DARK_OAK_BOAT = (33, "minecraft:dark_oak_boat", "Dark Oak Boat", "other", "Vehicles")
    DARK_OAK_CHEST_BOAT = (34, "minecraft:dark_oak_chest_boat", "Dark Oak Boat with Chest", "other", "Vehicles")
    DOLPHIN = (35, "minecraft:dolphin", "Dolphin", "passive", "Passive mobs")
    DONKEY = (36, "minecraft:donkey", "Donkey", "animal", "Passive mobs")
    DRAGON_FIREBALL = (37, "minecraft:dragon_fireball", "Dragon Fireball", "projectile", "Projectiles")
    DROWNED = (38, "minecraft:drowned", "Drowned", "hostile", "Hostile mobs")
    EGG = (39, "minecraft:egg", "Thrown Egg", "projectile", "Projectiles")
    ELDER_GUARDIAN = (40, "minecraft:elder_guardian", "Elder Guardian", "hostile", "Hostile mobs")
    ENDERMAN = (41, "minecraft:enderman", "Enderman", "hostile", "Hostile mobs")
    ENDERMITE = (42, "minecraft:endermite", "Endermite", "hostile", "Hostile mobs")
    ENDER_DRAGON = (43, "minecraft:ender_dragon", "Ender Dragon", "mob", "Hostile mobs")
    ENDER_PEARL = (44, "minecraft:ender_pearl", "Thrown Ender Pearl", "projectile", "Projectiles")
    END_CRYSTAL = (45, "minecraft:end_crystal", "End Crystal", "other", "Hostile mobs")
    EVOKER = (46, "minecraft:evoker", "Evoker", "hostile", "Hostile mobs")
    EVOKER_FANGS = (47, "minecraft:evoker_fangs", "Evoker Fangs", "other", "Projectiles")
    EXPERIENCE_BOTTLE = (48, "minecraft:experience_bottle", "Thrown Bottle o' Enchanting", "projectile", "Projectiles")
    EXPERIENCE_ORB = (49, "minecraft:experience_orb", "Experience Orb", "other", "UNKNOWN")
    EYE_OF_ENDER = (50, "minecraft:eye_of_ender", "Eye of Ender", "other", "Projectiles")
    FALLING_BLOCK = (51, "minecraft:falling_block", "Falling Block", "other", "UNKNOWN")
    FIREBALL = (52, "minecraft:fireball", "Fireball", "projectile", "Projectiles")
    FIREWORK_ROCKET = (53, "minecraft:firework_rocket", "Firework Rocket", "projectile", "Projectiles")
    FOX = (54, "minecraft:fox", "Fox", "animal", "Passive mobs")
    FROG = (55, "minecraft:frog", "Frog", "animal", "Passive mobs")
    FURNACE_MINECART = (56, "minecraft:furnace_minecart", "Minecart with Furnace", "other", "Vehicles")
    GHAST = (57, "minecraft:ghast", "Ghast", "mob", "Hostile mobs")
    HAPPY_GHAST = (58, "minecraft:happy_ghast", "Happy Ghast", "animal", "Passive mobs")
    GIANT = (59, "minecraft:giant", "Giant", "hostile", "Hostile mobs")
    GLOW_ITEM_FRAME = (60, "minecraft:glow_item_frame", "Glow Item Frame", "other", "Immobile")
    GLOW_SQUID = (61, "minecraft:glow_squid", "Glow Squid", "passive", "Passive mobs")
    GOAT = (62, "minecraft:goat", "Goat", "animal", "Passive mobs")
    GUARDIAN = (63, "minecraft:guardian", "Guardian", "hostile", "Hostile mobs")
    HOGLIN = (64, "minecraft:hoglin", "Hoglin", "animal", "Hostile mobs")
    HOPPER_MINECART = (65, "minecraft:hopper_minecart", "Minecart with Hopper", "other", "Vehicles")
    HORSE = (66, "minecraft:horse", "Horse", "animal", "Passive mobs")
    HUSK = (67, "minecraft:husk", "Husk", "hostile", "Hostile mobs")
    ILLUSIONER = (68, "minecraft:illusioner", "Illusioner", "hostile", "Hostile mobs")
    INTERACTION = (69, "minecraft:interaction", "Interaction", "other", "UNKNOWN")
    IRON_GOLEM = (70, "minecraft:iron_golem", "Iron Golem", "mob", "Passive mobs")
    ITEM = (71, "minecraft:item", "Item", "other", "UNKNOWN")
    ITEM_DISPLAY = (72, "minecraft:item_display", "Item Display", "other", "UNKNOWN")
    ITEM_FRAME = (73, "minecraft:item_frame", "Item Frame", "other", "Immobile")
    JUNGLE_BOAT = (74, "minecraft:jungle_boat", "Jungle Boat", "other", "Vehicles")
    JUNGLE_CHEST_BOAT = (75, "minecraft:jungle_chest_boat", "Jungle Boat with Chest", "other", "Vehicles")
    LEASH_KNOT = (76, "minecraft:leash_knot", "Leash Knot", "other", "Immobile")
    LIGHTNING_BOLT = (77, "minecraft:lightning_bolt", "Lightning Bolt", "other", "UNKNOWN")
    LLAMA = (78, "minecraft:llama", "Llama", "animal", "Passive mobs")
    LLAMA_SPIT = (79, "minecraft:llama_spit", "Llama Spit", "projectile", "Projectiles")
    MAGMA_CUBE = (80, "minecraft:magma_cube", "Magma Cube", "mob", "Hostile mobs")
    MANGROVE_BOAT = (81, "minecraft:mangrove_boat", "Mangrove Boat", "other", "Vehicles")
    MANGROVE_CHEST_BOAT = (82, "minecraft:mangrove_chest_boat", "Mangrove Boat with Chest", "other", "Vehicles")
    MANNEQUIN = (83, "minecraft:mannequin", "Mannequin", "living", "Immobile")
    MARKER = (84, "minecraft:marker", "Marker", "other", "UNKNOWN")
    MINECART = (85, "minecraft:minecart", "Minecart", "other", "Vehicles")
    MOOSHROOM = (86, "minecraft:mooshroom", "Mooshroom", "animal", "Passive mobs")
    MULE = (87, "minecraft:mule", "Mule", "animal", "Passive mobs")
    NAUTILUS = (88, "minecraft:nautilus", "Nautilus", "animal", "Passive mobs")
    OAK_BOAT = (89, "minecraft:oak_boat", "Oak Boat", "other", "Vehicles")
    OAK_CHEST_BOAT = (90, "minecraft:oak_chest_boat", "Oak Boat with Chest", "other", "Vehicles")
    OCELOT = (91, "minecraft:ocelot", "Ocelot", "animal", "Passive mobs")
    OMINOUS_ITEM_SPAWNER = (92, "minecraft:ominous_item_spawner", "Ominous Item Spawner", "other", "UNKNOWN")
    PAINTING = (93, "minecraft:painting", "Painting", "other", "Immobile")
    PALE_OAK_BOAT = (94, "minecraft:pale_oak_boat", "Pale Oak Boat", "other", "Vehicles")
    PALE_OAK_CHEST_BOAT = (95, "minecraft:pale_oak_chest_boat", "Pale Oak Boat with Chest", "other", "Vehicles")
    PANDA = (96, "minecraft:panda", "Panda", "animal", "Passive mobs")
    PARCHED = (97, "minecraft:parched", "Parched", "hostile", "Hostile mobs")
    PARROT = (98, "minecraft:parrot", "Parrot", "animal", "Passive mobs")
    PHANTOM = (99, "minecraft:phantom", "Phantom", "mob", "Hostile mobs")
    PIG = (100, "minecraft:pig", "Pig", "animal", "Passive mobs")
    PIGLIN = (101, "minecraft:piglin", "Piglin", "hostile", "Hostile mobs")
    PIGLIN_BRUTE = (102, "minecraft:piglin_brute", "Piglin Brute", "hostile", "Hostile mobs")
    PILLAGER = (103, "minecraft:pillager", "Pillager", "hostile", "Hostile mobs")
    POLAR_BEAR = (104, "minecraft:polar_bear", "Polar Bear", "animal", "Passive mobs")
    SPLASH_POTION = (105, "minecraft:splash_potion", "Splash Potion", "projectile", "Projectiles")
    LINGERING_POTION = (106, "minecraft:lingering_potion", "Lingering Potion", "projectile", "Projectiles")
    PUFFERFISH = (107, "minecraft:pufferfish", "Pufferfish", "mob", "Passive mobs")
    RABBIT = (108, "minecraft:rabbit", "Rabbit", "animal", "Passive mobs")
    RAVAGER = (109, "minecraft:ravager", "Ravager", "hostile", "Hostile mobs")
    SALMON = (110, "minecraft:salmon", "Salmon", "mob", "Passive mobs")
    SHEEP = (111, "minecraft:sheep", "Sheep", "animal", "Passive mobs")
    SHULKER = (112, "minecraft:shulker", "Shulker", "mob", "Hostile mobs")
    SHULKER_BULLET = (113, "minecraft:shulker_bullet", "Shulker Bullet", "projectile", "Projectiles")
    SILVERFISH = (114, "minecraft:silverfish", "Silverfish", "hostile", "Hostile mobs")
    SKELETON = (115, "minecraft:skeleton", "Skeleton", "hostile", "Hostile mobs")
    SKELETON_HORSE = (116, "minecraft:skeleton_horse", "Skeleton Horse", "animal", "Passive mobs")
    SLIME = (117, "minecraft:slime", "Slime", "mob", "Hostile mobs")
    SMALL_FIREBALL = (118, "minecraft:small_fireball", "Small Fireball", "projectile", "Projectiles")
    SNIFFER = (119, "minecraft:sniffer", "Sniffer", "animal", "Passive mobs")
    SNOWBALL = (120, "minecraft:snowball", "Snowball", "projectile", "Projectiles")
    SNOW_GOLEM = (121, "minecraft:snow_golem", "Snow Golem", "mob", "Passive mobs")
    SPAWNER_MINECART = (122, "minecraft:spawner_minecart", "Minecart with Monster Spawner", "other", "Vehicles")
    SPECTRAL_ARROW = (123, "minecraft:spectral_arrow", "Spectral Arrow", "projectile", "Projectiles")
    SPIDER = (124, "minecraft:spider", "Spider", "hostile", "Hostile mobs")
    SPRUCE_BOAT = (125, "minecraft:spruce_boat", "Spruce Boat", "other", "Vehicles")
    SPRUCE_CHEST_BOAT = (126, "minecraft:spruce_chest_boat", "Spruce Boat with Chest", "other", "Vehicles")
    SQUID = (127, "minecraft:squid", "Squid", "passive", "Passive mobs")
    STRAY = (128, "minecraft:stray", "Stray", "hostile", "Hostile mobs")
    STRIDER = (129, "minecraft:strider", "Strider", "animal", "Hostile mobs")
    TADPOLE = (130, "minecraft:tadpole", "Tadpole", "mob", "Passive mobs")
    TEXT_DISPLAY = (131, "minecraft:text_display", "Text Display", "other", "UNKNOWN")
    TNT = (132, "minecraft:tnt", "Primed TNT", "other", "UNKNOWN")
    TNT_MINECART = (133, "minecraft:tnt_minecart", "Minecart with TNT", "other", "Vehicles")
    TRADER_LLAMA = (134, "minecraft:trader_llama", "Trader Llama", "animal", "Passive mobs")
    TRIDENT = (135, "minecraft:trident", "Trident", "projectile", "Projectiles")
    TROPICAL_FISH = (136, "minecraft:tropical_fish", "Tropical Fish", "mob", "Passive mobs")
    TURTLE = (137, "minecraft:turtle", "Turtle", "animal", "Passive mobs")
    VEX = (138, "minecraft:vex", "Vex", "hostile", "Hostile mobs")
    VILLAGER = (139, "minecraft:villager", "Villager", "passive", "UNKNOWN")
    VINDICATOR = (140, "minecraft:vindicator", "Vindicator", "hostile", "Hostile mobs")
    WANDERING_TRADER = (141, "minecraft:wandering_trader", "Wandering Trader", "passive", "UNKNOWN")
    WARDEN = (142, "minecraft:warden", "Warden", "hostile", "Hostile mobs")
    WIND_CHARGE = (143, "minecraft:wind_charge", "Wind Charge", "projectile", "Projectiles")
    WITCH = (144, "minecraft:witch", "Witch", "hostile", "Hostile mobs")
    WITHER = (145, "minecraft:wither", "Wither", "hostile", "Hostile mobs")
    WITHER_SKELETON = (146, "minecraft:wither_skeleton", "Wither Skeleton", "hostile", "Hostile mobs")
    WITHER_SKULL = (147, "minecraft:wither_skull", "Wither Skull", "projectile", "Projectiles")
    WOLF = (148, "minecraft:wolf", "Wolf", "animal", "Passive mobs")
    ZOGLIN = (149, "minecraft:zoglin", "Zoglin", "hostile", "Hostile mobs")
    ZOMBIE = (150, "minecraft:zombie", "Zombie", "hostile", "Hostile mobs")
    ZOMBIE_HORSE = (151, "minecraft:zombie_horse", "Zombie Horse", "animal", "Passive mobs")
    ZOMBIE_NAUTILUS = (152, "minecraft:zombie_nautilus", "Zombie Nautilus", "animal", "Passive mobs")
    ZOMBIE_VILLAGER = (153, "minecraft:zombie_villager", "Zombie Villager", "hostile", "Hostile mobs")
    ZOMBIFIED_PIGLIN = (154, "minecraft:zombified_piglin", "Zombified Piglin", "hostile", "Hostile mobs")
    PLAYER = (155, "minecraft:player", "Player", "player", "UNKNOWN")
    FISHING_BOBBER = (156, "minecraft:fishing_bobber", "Fishing Bobber", "projectile", "Projectiles")
