"""Auto-generated from PrismarineJS/minecraft-data.
Minecraft Java Edition 1.21.11 — 115 particle types.

Each member's .value is the integer registry id for this version;
.string_id is the namespaced id (e.g. 'minecraft:flame').
NOTE: numeric ids are stable within a version but change between
versions (Java has no permanent numeric ids since 1.13).
Do not edit by hand; regenerate with _generate/particles.py."""

from grimmclub_standardlib import Enum


class Particle(Enum):
    def __new__(cls, num_id: int, string_id: str):
        obj = object.__new__(cls)
        obj._value_ = num_id
        obj.string_id = string_id
        return obj

    ANGRY_VILLAGER = (0, "minecraft:angry_villager")
    BLOCK = (1, "minecraft:block")
    BLOCK_MARKER = (2, "minecraft:block_marker")
    BUBBLE = (3, "minecraft:bubble")
    CLOUD = (4, "minecraft:cloud")
    COPPER_FIRE_FLAME = (5, "minecraft:copper_fire_flame")
    CRIT = (6, "minecraft:crit")
    DAMAGE_INDICATOR = (7, "minecraft:damage_indicator")
    DRAGON_BREATH = (8, "minecraft:dragon_breath")
    DRIPPING_LAVA = (9, "minecraft:dripping_lava")
    FALLING_LAVA = (10, "minecraft:falling_lava")
    LANDING_LAVA = (11, "minecraft:landing_lava")
    DRIPPING_WATER = (12, "minecraft:dripping_water")
    FALLING_WATER = (13, "minecraft:falling_water")
    DUST = (14, "minecraft:dust")
    DUST_COLOR_TRANSITION = (15, "minecraft:dust_color_transition")
    EFFECT = (16, "minecraft:effect")
    ELDER_GUARDIAN = (17, "minecraft:elder_guardian")
    ENCHANTED_HIT = (18, "minecraft:enchanted_hit")
    ENCHANT = (19, "minecraft:enchant")
    END_ROD = (20, "minecraft:end_rod")
    ENTITY_EFFECT = (21, "minecraft:entity_effect")
    EXPLOSION_EMITTER = (22, "minecraft:explosion_emitter")
    EXPLOSION = (23, "minecraft:explosion")
    GUST = (24, "minecraft:gust")
    SMALL_GUST = (25, "minecraft:small_gust")
    GUST_EMITTER_LARGE = (26, "minecraft:gust_emitter_large")
    GUST_EMITTER_SMALL = (27, "minecraft:gust_emitter_small")
    SONIC_BOOM = (28, "minecraft:sonic_boom")
    FALLING_DUST = (29, "minecraft:falling_dust")
    FIREWORK = (30, "minecraft:firework")
    FISHING = (31, "minecraft:fishing")
    FLAME = (32, "minecraft:flame")
    INFESTED = (33, "minecraft:infested")
    CHERRY_LEAVES = (34, "minecraft:cherry_leaves")
    PALE_OAK_LEAVES = (35, "minecraft:pale_oak_leaves")
    TINTED_LEAVES = (36, "minecraft:tinted_leaves")
    SCULK_SOUL = (37, "minecraft:sculk_soul")
    SCULK_CHARGE = (38, "minecraft:sculk_charge")
    SCULK_CHARGE_POP = (39, "minecraft:sculk_charge_pop")
    SOUL_FIRE_FLAME = (40, "minecraft:soul_fire_flame")
    SOUL = (41, "minecraft:soul")
    FLASH = (42, "minecraft:flash")
    HAPPY_VILLAGER = (43, "minecraft:happy_villager")
    COMPOSTER = (44, "minecraft:composter")
    HEART = (45, "minecraft:heart")
    INSTANT_EFFECT = (46, "minecraft:instant_effect")
    ITEM = (47, "minecraft:item")
    VIBRATION = (48, "minecraft:vibration")
    TRAIL = (49, "minecraft:trail")
    ITEM_SLIME = (50, "minecraft:item_slime")
    ITEM_COBWEB = (51, "minecraft:item_cobweb")
    ITEM_SNOWBALL = (52, "minecraft:item_snowball")
    LARGE_SMOKE = (53, "minecraft:large_smoke")
    LAVA = (54, "minecraft:lava")
    MYCELIUM = (55, "minecraft:mycelium")
    NOTE = (56, "minecraft:note")
    POOF = (57, "minecraft:poof")
    PORTAL = (58, "minecraft:portal")
    RAIN = (59, "minecraft:rain")
    SMOKE = (60, "minecraft:smoke")
    WHITE_SMOKE = (61, "minecraft:white_smoke")
    SNEEZE = (62, "minecraft:sneeze")
    SPIT = (63, "minecraft:spit")
    SQUID_INK = (64, "minecraft:squid_ink")
    SWEEP_ATTACK = (65, "minecraft:sweep_attack")
    TOTEM_OF_UNDYING = (66, "minecraft:totem_of_undying")
    UNDERWATER = (67, "minecraft:underwater")
    SPLASH = (68, "minecraft:splash")
    WITCH = (69, "minecraft:witch")
    BUBBLE_POP = (70, "minecraft:bubble_pop")
    CURRENT_DOWN = (71, "minecraft:current_down")
    BUBBLE_COLUMN_UP = (72, "minecraft:bubble_column_up")
    NAUTILUS = (73, "minecraft:nautilus")
    DOLPHIN = (74, "minecraft:dolphin")
    CAMPFIRE_COSY_SMOKE = (75, "minecraft:campfire_cosy_smoke")
    CAMPFIRE_SIGNAL_SMOKE = (76, "minecraft:campfire_signal_smoke")
    DRIPPING_HONEY = (77, "minecraft:dripping_honey")
    FALLING_HONEY = (78, "minecraft:falling_honey")
    LANDING_HONEY = (79, "minecraft:landing_honey")
    FALLING_NECTAR = (80, "minecraft:falling_nectar")
    FALLING_SPORE_BLOSSOM = (81, "minecraft:falling_spore_blossom")
    ASH = (82, "minecraft:ash")
    CRIMSON_SPORE = (83, "minecraft:crimson_spore")
    WARPED_SPORE = (84, "minecraft:warped_spore")
    SPORE_BLOSSOM_AIR = (85, "minecraft:spore_blossom_air")
    DRIPPING_OBSIDIAN_TEAR = (86, "minecraft:dripping_obsidian_tear")
    FALLING_OBSIDIAN_TEAR = (87, "minecraft:falling_obsidian_tear")
    LANDING_OBSIDIAN_TEAR = (88, "minecraft:landing_obsidian_tear")
    REVERSE_PORTAL = (89, "minecraft:reverse_portal")
    WHITE_ASH = (90, "minecraft:white_ash")
    SMALL_FLAME = (91, "minecraft:small_flame")
    SNOWFLAKE = (92, "minecraft:snowflake")
    DRIPPING_DRIPSTONE_LAVA = (93, "minecraft:dripping_dripstone_lava")
    FALLING_DRIPSTONE_LAVA = (94, "minecraft:falling_dripstone_lava")
    DRIPPING_DRIPSTONE_WATER = (95, "minecraft:dripping_dripstone_water")
    FALLING_DRIPSTONE_WATER = (96, "minecraft:falling_dripstone_water")
    GLOW_SQUID_INK = (97, "minecraft:glow_squid_ink")
    GLOW = (98, "minecraft:glow")
    WAX_ON = (99, "minecraft:wax_on")
    WAX_OFF = (100, "minecraft:wax_off")
    ELECTRIC_SPARK = (101, "minecraft:electric_spark")
    SCRAPE = (102, "minecraft:scrape")
    SHRIEK = (103, "minecraft:shriek")
    EGG_CRACK = (104, "minecraft:egg_crack")
    DUST_PLUME = (105, "minecraft:dust_plume")
    TRIAL_SPAWNER_DETECTION = (106, "minecraft:trial_spawner_detection")
    TRIAL_SPAWNER_DETECTION_OMINOUS = (107, "minecraft:trial_spawner_detection_ominous")
    VAULT_CONNECTION = (108, "minecraft:vault_connection")
    DUST_PILLAR = (109, "minecraft:dust_pillar")
    OMINOUS_SPAWNING = (110, "minecraft:ominous_spawning")
    RAID_OMEN = (111, "minecraft:raid_omen")
    TRIAL_OMEN = (112, "minecraft:trial_omen")
    BLOCK_CRUMBLE = (113, "minecraft:block_crumble")
    FIREFLY = (114, "minecraft:firefly")
