"""grimmcraft-control — a pure, type-safe state-machine controller.

The controller lives in the :mod:`grimmcraft_control.machine` subpackage; its
public API is re-exported here for convenience.  Ready-made example machines
(door, furnace) live in :mod:`grimmcraft_control.demos`.
"""

from __future__ import annotations

from grimmcraft_control.machine import (
    STATE_OBJECTIVE,
    TICK_EVENT,
    Action,
    Command,
    CommandBus,
    CommandHandler,
    CommandName,
    Condition,
    ConditionName,
    Event,
    Guard,
    GuardError,
    InvalidTransition,
    Machine,
    MachineBuilder,
    MachineBuildError,
    Result,
    State,
    StateDraft,
    StateMachineError,
    Transition,
    TransitionDraft,
    add_score,
    give,
    new_machine,
    particle,
    playsound,
    say,
    set_score,
    setblock,
    summon,
    tellraw,
)

__all__ = [
    "State",
    "Event",
    "Transition",
    "Condition",
    "Guard",
    "Action",
    "Command",
    "CommandName",
    "ConditionName",
    "CommandHandler",
    "CommandBus",
    "Result",
    "Machine",
    "MachineBuilder",
    "new_machine",
    "StateDraft",
    "TransitionDraft",
    "STATE_OBJECTIVE",
    "TICK_EVENT",
    "StateMachineError",
    "MachineBuildError",
    "InvalidTransition",
    "GuardError",
    "setblock",
    "say",
    "tellraw",
    "playsound",
    "particle",
    "summon",
    "give",
    "set_score",
    "add_score",
]
